name: Ubuntu SSH

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Start with b164a616a8831ab6ac92b6aceb91f5e3b7bab82b Git-Ref (Focal)
        required: false

jobs:
  ssh:
    runs-on: ubuntu-18.04

    env:
      GitHubMail: ${{ secrets.GitHubMail }}
      GitHubName: ${{ secrets.GitHubName }}

    steps:
      - uses: actions/checkout@main
        if: github.event.inputs.git-ref == ''

      - uses: actions/checkout@main
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
      #- uses: rokibhasansagar/slimhub_actions@main
      - run: printenv | sort
      - name: SSH Keepalive
        run: |
          mkdir -p ~/.ssh
          cat << EOF > ~/.ssh/config
          Host *
              ServerAliveInterval 60
              StrictHostKeyChecking no
          Host github.com
              User git
              Port 22
              Hostname github.com
              TCPKeepAlive yes
              IdentitiesOnly yes
          EOF
      - name: SSH connection to Actions
        continue-on-error: true
        timeout-minutes: 340
        uses: P3TERX/ssh2actions@main
        with:
          mode: ngrok
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          NGROK_REGION: us
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
